"""Generate the x16 / x32 train and test configs from the x4 ones (rerun after changing an x4 recipe).

    python scripts/make_scale_configs.py            # writes options/{train,test}/*/*x16*, *x32*

Both scales are powers of 2, so every network supports them natively (pixel-shuffle x2 stages; RRDBNet one nearest x2
+ conv stage per factor 2). Differences from x4 (everything else, e.g. optimiser, losses, budget, batch 16, is kept):
* random crops (BasicSR ``gt_size``) instead of whole tiles: LR 32 px (x16) / 16 px (x32) -> HR 512 px, because whole
  768 / 1536 px targets do not fit a batch of 16;
* network scale (``scale`` / ``upscale``; SwinIR ``img_size`` = LR crop, also in the test configs because its attention
  masks are sized by it); ESRGAN discriminator input 512 (= the HR crop); ``crop_border`` = scale; validation / test
  batch 2 (whole tiles).
AdcSR stays x4 (its input stage is built for x4).
"""
import os
import re
from os import path as osp

ROOT = osp.dirname(osp.dirname(osp.abspath(__file__)))
LR_CROP = {16: 32, 32: 16}
TRAIN = ['Baseline/train_Bicubic_x4.yml', 'ESRGAN/train_RRDBNet_PSNR_x4.yml', 'ESRGAN/train_ESRGAN_x4.yml',
         'SwinIR/train_SwinIR_SRx4_scratch.yml', 'EDSR/train_EDSR_Lx4.yml', 'EDSR/train_EDSR_Mx4.yml']
TEST = ['Baseline/test_Bicubic_x4.yml', 'ESRGAN/test_RRDBNet_PSNR_x4.yml', 'ESRGAN/test_ESRGAN_x4.yml',
        'SwinIR/test_SwinIR_SRx4.yml', 'EDSR/test_EDSR_Lx4.yml', 'EDSR/test_EDSR_Mx4.yml']


def sub(line, pattern, repl):
    new = re.sub(pattern, repl, line)
    assert new != line, (pattern, line)
    return new


def rename(text, s):
    """x4 -> x{s} in run names and paths (and SwinIR's patch tag P48 -> P{lr})."""
    text = re.sub(r'(?<=[_A-Za-z])x4(?=_)', f'x{s}', text)
    return text.replace('P48W8', f'P{LR_CROP[s]}W8')


def convert(src, s, train):
    lr = LR_CROP[s]
    hr = lr * s
    out, section, sub_section = [], None, None
    out.append(f'# [x{s} variant of {osp.basename(src)}, generated by scripts/make_scale_configs.py'
               + ('; the header below describes x4]\n' if train else ']\n'))
    if train:
        out.append(f'# x{s}: random crops LR {lr} px -> HR {hr} px (x4: whole tiles); validation on whole tiles '
                   f'(48 -> {48 * s} px).\n')
    for line in open(src):
        stripped = line.rstrip('\n')
        if re.match(r'^\S', stripped):  # top-level key
            section = stripped.split(':')[0]
        if re.match(r'^  (train|val|test_\d+):', stripped) and section == 'datasets':
            sub_section = stripped.strip()[:-1]
        if stripped.startswith('name:') or 'pretrain_network_g:' in stripped:
            line = rename(line, s)
        elif stripped.startswith('scale: 4'):
            line = sub(line, r'^scale: 4', f'scale: {s}')
        elif re.match(r'^  (scale|upscale): 4\b', stripped):
            line = sub(line, r': 4\b', f': {s}')
        elif stripped.startswith('  img_size: 48'):
            line = sub(line, r'img_size: 48', f'img_size: {lr}')
        elif stripped.startswith('  input_size: 192'):
            line = sub(line, r'input_size: 192', f'input_size: {hr}')
        elif stripped.lstrip().startswith('crop_border: 4'):
            line = sub(line, r'crop_border: 4', f'crop_border: {s}')
        elif stripped.startswith('    gt_size:'):
            line = f'    gt_size: {hr}           # random HR crop of LR {lr} px\n'
        elif stripped.startswith('    batch_size_per_gpu: 16') and (not train or sub_section == 'val'):
            line = sub(line, r'16', '2')
        out.append(line)
    return ''.join(out)


def main():
    written = []
    for kind, files in (('train', TRAIN), ('test', TEST)):
        for rel in files:
            src = osp.join(ROOT, 'options', kind, rel)
            for s in LR_CROP:
                dst = osp.join(osp.dirname(src), osp.basename(src).replace('x4', f'x{s}'))
                with open(dst, 'w') as f:
                    f.write(convert(src, s, kind == 'train'))
                written.append(osp.relpath(dst, ROOT))
    print('\n'.join(written))
    print(f'{len(written)} configs written')


if __name__ == '__main__':
    os.chdir(ROOT)
    main()
