"""Generate the ``*_pretrained`` train and test configs from the scratch ones (rerun after changing a scratch config or
after scripts/make_scale_configs.py).

    python scripts/make_pretrained_configs.py       # writes options/{train,test}/*/*_pretrained.yml

A pretrained run differs from its scratch run only in the initialisation (data, recipe and budget are unchanged):
* ``path.pretrain_network_g``: official RGB weights (scripts/download_pretrained.py); SwinIR uses its ×4 model at ×4 and
  its ×8 model at ×8 / ×16 / ×32, RRDBNet and EDSR their ×4 models at every scale;
* ``path.pretrain_rgb_input``: conv_first's RGB filters go to B04 / B03 / B02 (the other bands start at 0), with the
  band normalisation folded in so that the RGB model sees the S2 RGB colour-matched to Maxar (mean / std of the Maxar
  targets, ``maxar_mean`` / ``maxar_std`` in datasets/s2maxar/stats.json); see srbench/models/base_model.py
  ``inflate_rgb_input``;
* ``strict_load_g: false``: layers missing from the checkpoint (the ×2 stages above its scale) stay randomly
  initialised; SwinIR's attention-mask buffers differ in size below img_size 48 and are rebuilt, not loaded;
* ESRGAN stage 2 starts from the pretrained stage-1 run instead of the scratch one;
* run names get the suffix ``_pretrained`` (own experiments/ and results/ folders).
The Bicubic baseline (no pretrained weights) and AdcSR (pretrained by design) have no such variant.
"""
import json
import os
import re
from os import path as osp

ROOT = osp.dirname(osp.dirname(osp.abspath(__file__)))
SCALES = (4, 8, 16, 32)
W = 'experiments/pretrained_models/'
SWINIR = W + '001_classicalSR_DIV2K_s48w8_SwinIR-M_x{}.pth'
# scratch train config: weights per scale (None: ESRGAN stage 2, initialised from the pretrained stage-1 run)
TRAIN = {
    'ESRGAN/train_RRDBNet_PSNR_x{}.yml': lambda s: W + 'ESRGAN_PSNR_SRx4_DF2K_official.pth',
    'ESRGAN/train_ESRGAN_x{}.yml': lambda s: None,
    'SwinIR/train_SwinIR_SRx{}_scratch.yml': lambda s: SWINIR.format(4 if s == 4 else 8),
    'EDSR/train_EDSR_Lx{}.yml': lambda s: W + 'EDSR_Lx4_f256b32_DIV2K_official.pth',
    'EDSR/train_EDSR_Mx{}.yml': lambda s: W + 'EDSR_Mx4_f64b16_DIV2K_official.pth',
}
DIV2K_MEAN = [0.4488, 0.4371, 0.4040]  # subtracted from the input by the RGB EDSR / SwinIR models (RRDBNet: nothing)
TEST = ['ESRGAN/test_RRDBNet_PSNR_x{}.yml', 'ESRGAN/test_ESRGAN_x{}.yml', 'SwinIR/test_SwinIR_SRx{}.yml',
        'EDSR/test_EDSR_Lx{}.yml', 'EDSR/test_EDSR_Mx{}.yml']


def out_name(rel):
    base = rel.replace('_scratch.yml', '.yml')
    return base[:-len('.yml')] + '_pretrained.yml'


def rgb_input_block(rel, stats):
    lines = ['  pretrain_rgb_input:  # RGB filters of conv_first -> B04, B03, B02 (other bands start at 0), docs/02 §2.2',
             '    channels: [3, 2, 1]',
             f"    mean: {stats['maxar_mean']}  # a z-scored band is shown to the RGB model as mean + std * z",
             f"    std: {stats['maxar_std']}  # (Maxar RGB statistics, datasets/s2maxar/stats.json)"]
    if 'RRDBNet' not in rel:
        lines.append(f'    rgb_mean: {DIV2K_MEAN}  # subtracted from the input by the RGB model (DIV2K mean)')
    return '\n'.join(lines) + '\n'


def convert(rel, text, weights, train, stats):
    """Return the pretrained variant of one scratch config."""
    assert 'lq_bands' not in text or re.search(r'lq_bands: ~', text), f'{rel}: RGB channels assume all 12 bands'
    head = f'# [pretrained-init variant of {osp.basename(rel)}, generated by scripts/make_pretrained_configs.py'
    head += '; the header below describes the scratch run]\n' if train else ']\n'
    if train and weights:
        head += (f'# init: {osp.basename(weights)} (official RGB model, scripts/download_pretrained.py); recipe as '
                 'in the scratch run.\n')
    elif train:
        head += '# init: the pretrained stage-1 run (RRDBNet_PSNR ..._pretrained); recipe as in the scratch run.\n'
    text = re.sub(r'^name: (\S+)', r'name: \1_pretrained', text, count=1, flags=re.M)
    if weights:
        text, n = re.subn(
            r'^  pretrain_network_g: ~\n  strict_load_g: true\n',
            f'  pretrain_network_g: {weights}\n' + rgb_input_block(rel, stats) +
            '  strict_load_g: false  # layers missing from the checkpoint (x2 stages above its scale) stay random\n',
            text, flags=re.M)
    else:  # ESRGAN stage 2 and test configs: the pretrained run of the same model
        text, n = re.subn(r'^(  pretrain_network_g: experiments/)([^/\s]+)(/models/)', r'\1\2_pretrained\3', text,
                          flags=re.M)
    assert n == 1, f'{rel}: path section not recognised'
    return head + text


def main():
    with open(osp.join(ROOT, 'datasets', 's2maxar', 'stats.json')) as f:
        stats = json.load(f)
    written = []
    for kind, entries in (('train', TRAIN), ('test', dict.fromkeys(TEST))):
        for pattern, weights in entries.items():
            for s in SCALES:
                rel = pattern.format(s)
                with open(osp.join(ROOT, 'options', kind, rel)) as f:
                    text = f.read()
                dst = osp.join(ROOT, 'options', kind, out_name(rel))
                with open(dst, 'w') as f:
                    f.write(convert(rel, text, weights(s) if weights else None, kind == 'train', stats))
                written.append(osp.relpath(dst, ROOT))
    print('\n'.join(written))
    print(f'{len(written)} configs written')


if __name__ == '__main__':
    os.chdir(ROOT)
    main()
